countries=("India","USA","UK","Japan","China","Russia","Pakistan","Sri Lanka","Bangladesh","Nepal")
temp = list(countries)
print(countries)
print(temp)
temp.append("Bhutan")
temp.pop(3)
countries=tuple(temp)
print(countries)
print(countries.index("China"))
print(countries.count("India"))
print(len(countries))
countries2=("Germany","France")
countries3=countries+countries2
print(countries3)
